### ISSUE TITLE
`generic_ec_zkp::polynomial::lagrange_coefficient` should accept nullable scalars as well

### ISSUE THREAD

**Issue by maurges** [dfns/generic-ec#26]
Sometimes we want to do interpolations for values with zero being known, like in our new (secret) protocol. I suggest a new signature, directly copied from there:

```
fn lagrange_coefficient<E: Curve, S: AsRef<Scalar<E>>>(
    x: Scalar<E>,
    j: usize,
    xs: &[S],
) -> Option<Scalar<E>> {
```

**Comment by survived** [comment]
Yea, that makes sense. Originally, I designed it to accept non-zeroes only because it was supposed to be used only in secret sharings (well, in simpler versions of secret sharing than what you're working on). Now it's clear that it should accept any scalars.
